### PR TITLE
[WIP] Vendor WebKit for fully static JavaScriptCore builds

### PR DESCRIPTION
**Pull request by jviotti**
Signed-off-by: Juan Cruz Viotti <jv@jviotti.com>

### CODE REVIEW

**Comment by bavulapati** [comment]
@jviotti How do I get started?
Can you give me the steps to start?

**Comment by bavulapati** [comment]
> @jviotti How do I get started? Can you help me with the steps to start?

I can see that it's got a makefile!

**Comment by bavulapati** [comment]
I have another question - why do we prefer static JSC build?

**Comment by jviotti** [comment]
> I have another question - why do we prefer static JSC build?

For more easier distribution. Then we can distribute a single shared/static library of *both* IncludeJS + JavaScriptCore instead of separated.

**Comment by bavulapati** [comment]
@jviotti we are deleting the build folder after pulling the ICU dependencies

**Comment by RaisinTen** [comment]
Do we really need to vendor JSC for this? Can't we use the prebuilt binaries from https://github.com/bavulapati/JavaScriptCore?

**Comment by jviotti** [comment]
I much rather vendor here and we publish prebuilt binaries out of this repo instead, in the same way, but `.lib` and `.dll` if IncludeJS

**Comment by jviotti** [comment]
Yeah, that's indeed a lot. So then what I propose is for @bavulapati to move his JavaScriptCore repo that produces pre-made static/shared debug/release libraries to this org instead, so we have control over how they are produced. 

What do you think?

**Comment by jviotti** [comment]
I'll close this PR then, and we can handle moving https://github.com/bavulapati/JavaScriptCore here.

**Comment by RaisinTen** [comment]
Sounds good to me!

**Pull request closed without merging**
