### PR TITLE
ci: enable asan and ubs

### PR DESCRIPTION
**Pull request by tony-go**

### CODE REVIEW

**Comment by jviotti** [comment]
Interesting. You can do a GoogleTest `vendorpull` patch, but I believe there are also ways to instruct the sanitizers to ignore certain files/symbols, i.e. passing an exclude

**Comment by tony-go** [comment]
Unfortunately, I did not manage to find a way to exclude it for a few reasons:

- The file that has an issue is `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__functional/hash.h:107:40`  I don't know how to exclude it, should I use `hash.h`?

- Which rule should I disable? According to the documentation, I tried `shift-base` and `shift-exponent`: https://releases.llvm.org/3.8.0/tools/clang/docs/UndefinedBehaviorSanitizer.html#availablle-checks

The doc is thin. I also searched on github.

I open an issue on LLVM https://github.com/llvm/llvm-project/issues/82500

**Comment by jviotti** [comment]
To be honest, not sure from the top of my head, but I think you are on the right track. Let's see if LLVM responds and I can try to help if it remains a problem

**Comment by tony-go** [comment]
Hey @jviotti 

Finally solved it :)

**Review by jviotti — APPROVED** [review]
Awesome!

**Pull request merged**
